server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/proym3
    username: postgres
    password: jhon102030
jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect